; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                      = 10180924-x86_64 Linux                   
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
[ ProcessTypes ]
ppDistEst                                = true                                    
ppOverallMean                            = true                                    
[ AnalysisSettings ]
Analysis                                 = Distance Estimation                     
Scope                                    = Overall Mean                            
Estimate Variance                        = ====================                    
Variance Estimation Method               = Bootstrap method                        
No. of Bootstrap Replications            = 500                                     
Substitution Model                       = ====================                    
Substitutions Type                       = Syn-Nonsynonymous                       
Model/Method                             = Modified Nei-Gojobori method (Jukes-Cantor)
Fixed Transition/Transversion Ratio      = 2.00                                    
Substitutions to Include                 = s: Synonymous only                      
Rates and Patterns                       = ====================                    
Rates among Sites                        = Gamma Distributed (G)                   
Gamma Parameter                          = 1.00                                    
Pattern among Lineages                   = Same (Homogeneous)                      
Data Subset to Use                       = ====================                    
Gaps/Missing Data Treatment              = Pairwise deletion                       
Site Coverage Cutoff (%)                 = Not Applicable                          
Select Codon Positions                   = 1st, 2nd, 3rd, Non-Coding               
Genetic Code Table                       = Standard                                
Genetic Code                             = FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
